# 这是一个 matugen 配置文件 (config.toml)
# 占位符 './templates/' 代表模板的源目录
# 占位符 '/./colors-apply.sh' 代表 QML 脚本中的 'colorsApplyScript'

[config]
#... 可以在这里添加 matugen 的全局配置...

# --- GTK ---
# 源 JSON 'gtk' 块被拆分为 gtk3 和 gtk4
[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
# post_hook 应用于此模板块 
#post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
# post_hook = 'gsettings set org.gnome.desktop.interface color-scheme prefer-{{mode}}'


# --- Qt ---
# 源 JSON 'qt' 块被拆分为 qt5 和 qt6
[templates.qt5]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/noctalia.conf'

[templates.qt6]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/noctalia.conf'

# --- KColorScheme ---
[templates.kcolorscheme]
input_path = './templates/kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/noctalia.colors'

# --- KDE ---
[templates.KDE]
input_path = './templates/kcolorscheme.colors'
output_path = '~/.config/kdeglobals'

# --- Fuzzel ---
[templates.fuzzel]
input_path = './templates/fuzzel.conf'
output_path = '~/.config/fuzzel/themes/noctalia'
post_hook = 'bash ~/.local/share/gnome-shell/extensions/matugen-autothemer@material-you/matugen/bin/colors-apply.sh fuzzel'

# --- Pywalfox ---
[templates.pywalfox]
input_path = './templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'bash ~/.local/share/gnome-shell/extensions/matugen-autothemer@material-you/matugen/bin/colors-apply.sh pywalfox'

# --- Discord (Vesktop) ---
[templates.discord_vesktop]
input_path = './templates/vesktop.css'
output_path = '~/.config/vesktop/themes/noctalia.theme.css'

# --- Discord (Webcord) ---
[templates.discord_webcord]
input_path = './templates/vesktop.css'
output_path = '~/.config/webcord/themes/noctalia.theme.css'

# --- Discord (Armcord) ---
[templates.discord_armcord]
input_path = './templates/vesktop.css'
output_path = '~/.config/armcord/themes/noctalia.theme.css'

# --- Discord (Equibop) ---
[templates.discord_equibop]
input_path = './templates/vesktop.css'
output_path = '~/.config/equibop/themes/noctalia.theme.css'

# --- Discord (Lightcord) ---
[templates.discord_lightcord]
input_path = './templates/vesktop.css'
output_path = '~/.config/lightcord/themes/noctalia.theme.css'

# --- Discord (Dorion) ---
[templates.discord_dorion]
input_path = './templates/vesktop.css'
output_path = '~/.config/dorion/themes/noctalia.theme.css'

# --- Discord (Vencord) ---
[templates.discord_vencord]
input_path = './templates/vesktop.css'
output_path = '~/.config/discord/themes/noctalia.theme.css'

# --- Vicinae ---
[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'bash ~/.local/share/gnome-shell/extensions/matugen-autothemer@material-you/matugen/bin/colors-apply.sh vicinae'

# --- Walker ---
[templates.walker]
input_path = './templates/walker.css'
output_path = '~/.config/walker/themes/noctalia/style.css'
post_hook = 'bash ~/.local/share/gnome-shell/extensions/matugen-autothemer@material-you/matugen/bin/colors-apply.sh walker'

# --- VSCode ---
[templates.code]
input_path = './templates/code.json'
output_path = '~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json'

[templates.zed]
input_path = './templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.ghostty]
input_path = './templates/Terminal/ghostty'
output_path = '~/.config/ghostty/themes/noctalia'

[templates.gnomeshell]
input_path = './templates/gnome-shell-colors.scss'
output_path= './templates/gnome-shell-sass/_colors.scss'
post_hook = "sassc ~/.local/share/gnome-shell/extensions/matugen-autothemer@material-you/matugen/templates/gnome-shell.scss ~/.local/share/themes/Material/gnome-shell/gnome-shell.css && gsettings set org.gnome.desktop.interface color-scheme prefer-{{mode | lower_case}}"